{
  "_id": {
    "$oid": "6071e39d43dd71267de1c3ea"
  },
  "author_association": "COLLABORATOR",
  "issue_url": "https://api.github.com/repos/pydanny/cookiecutter-django/issues/1118",
  "updated_at": "2017-04-12T12:59:29Z",
  "performed_via_github_app": null,
  "html_url": "https://github.com/pydanny/cookiecutter-django/issues/1118#issuecomment-293567735",
  "created_at": "2017-04-12T12:59:29Z",
  "id": 293567735,
  "body": "Weird. I could not reproduce the error. You could try to create a new clean virtualenv, and install cookiecutter and try again?\r\n\r\nPlease install cookiecutter with the pip `--upgrade --no-cache-dir --force-reinstall` option, to force re-download packages and reinstall all packages.\r\n\r\n```\r\npip install \"cookiecutter>=1.5.1\" --upgrade --no-cache-dir --force-reinstall\r\n```\r\n",
  "user": {
    "gists_url": "https://api.github.com/users/luzfcb/gists{/gist_id}",
    "repos_url": "https://api.github.com/users/luzfcb/repos",
    "following_url": "https://api.github.com/users/luzfcb/following{/other_user}",
    "starred_url": "https://api.github.com/users/luzfcb/starred{/owner}{/repo}",
    "login": "luzfcb",
    "followers_url": "https://api.github.com/users/luzfcb/followers",
    "type": "User",
    "url": "https://api.github.com/users/luzfcb",
    "subscriptions_url": "https://api.github.com/users/luzfcb/subscriptions",
    "received_events_url": "https://api.github.com/users/luzfcb/received_events",
    "avatar_url": "https://avatars.githubusercontent.com/u/807599?v=4",
    "events_url": "https://api.github.com/users/luzfcb/events{/privacy}",
    "html_url": "https://github.com/luzfcb",
    "site_admin": false,
    "id": 807599,
    "gravatar_id": "",
    "node_id": "MDQ6VXNlcjgwNzU5OQ==",
    "organizations_url": "https://api.github.com/users/luzfcb/orgs"
  },
  "url": "https://api.github.com/repos/pydanny/cookiecutter-django/issues/comments/293567735",
  "node_id": "MDEyOklzc3VlQ29tbWVudDI5MzU2NzczNQ=="
}